import { zzfx } from 'zzfx';

export class SoundManager {
  private scene: Phaser.Scene | null = null;
  private sounds: Map<string, Phaser.Sound.BaseSound> = new Map();
  private musicVolume = 0.3;
  private sfxVolume = 0.5;
  private musicMuted = false;
  private sfxMuted = false;
  private audioLoaded = false;
  private audioLoading = false;

  constructor() {
    // Load settings from localStorage
    this.loadSettings();
  }

  private loadSettings() {
    const savedMusicVolume = localStorage.getItem('musicVolume');
    const savedSfxVolume = localStorage.getItem('sfxVolume');
    const savedMusicEnabled = localStorage.getItem('musicEnabled');
    const savedSfxEnabled = localStorage.getItem('sfxEnabled');

    if (savedMusicVolume) this.musicVolume = Number(savedMusicVolume) / 100;
    if (savedSfxVolume) this.sfxVolume = Number(savedSfxVolume) / 100;
    if (savedMusicEnabled) this.musicMuted = savedMusicEnabled !== 'true';
    if (savedSfxEnabled) this.sfxMuted = savedSfxEnabled !== 'true';
  }

  // ZzFX sound effect definitions (arcade-style retro sounds)
  private zzfxSounds = {
    placeProduct: () => zzfx(this.sfxVolume, 0, 523, .01, .04, .05, 1, 1.7, 0, 0, 0, 0, 0, 0, 0, 0, 0, .5, .01), // Pop
    enemyHit: () => zzfx(this.sfxVolume, 0, 130, .01, 0, .09, 0, 1.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, .5, 0), // Hit
    enemyKill: () => zzfx(this.sfxVolume, 0, 330, .06, .16, .29, 1, 1.6, 0, 6.27, -184, .09, .17, 0, 0, 0, 0, .55, .04), // Explosion
    itemStolen: () => zzfx(this.sfxVolume, 0, 440, .02, .08, .2, 3, 1.4, -1, 0, 0, 0, 0, .5, 0, 0, 0, .5, .02), // Negative
    levelComplete: () => zzfx(this.sfxVolume, 0, 830, .04, .12, .3, 0, 2, 0, 0, 0, 0, 0, 0, 0, .1, 0, .7, .04), // Victory
    rareItem: () => zzfx(this.sfxVolume, 0, 1319, .03, .1, .3, 0, 2.5, 5, 0, 0, 0, 0, 0, 0, 0, 0, .6, .05), // Sparkle
  };

  init(scene: Phaser.Scene) {
    this.scene = scene;
  }

  preload(scene: Phaser.Scene) {
    // Only preload background music (sound effects are generated by ZzFX)
    scene.load.audio('bgMusic', '/sounds/background-music.mp3');
  }

  /**
   * Load audio asynchronously in the background without blocking game start
   */
  async preloadAsync(scene: Phaser.Scene) {
    if (this.audioLoading || this.audioLoaded) return;
    
    this.audioLoading = true;
    
    try {
      // Use Phaser's loader to load audio dynamically after game start
      scene.load.once('complete', () => {
        this.audioLoaded = true;
        console.log('Background music loaded successfully');
      });
      
      scene.load.once('loaderror', () => {
        console.warn('Failed to preload background music');
        this.audioLoaded = false;
      });
      
      scene.load.audio('bgMusic', '/sounds/background-music.mp3');
      scene.load.start(); // Manually start the loader
    } catch (error) {
      console.warn('Failed to preload background music:', error);
      this.audioLoaded = false;
    } finally {
      this.audioLoading = false;
    }
  }

  playBackgroundMusic() {
    if (!this.scene || this.musicMuted) return;
    
    // Wait for audio to be loaded before attempting to play
    if (!this.audioLoaded) {
      // Retry after audio loads
      const checkAndPlay = () => {
        if (this.audioLoaded && !this.musicMuted) {
          this.playBackgroundMusic();
        }
      };
      setTimeout(checkAndPlay, 500);
      return;
    }
    
    if (!this.sounds.has('bgMusic')) {
      try {
        const music = this.scene.sound.add('bgMusic', {
          loop: true,
          volume: this.musicVolume,
        });
        this.sounds.set('bgMusic', music);
      } catch (error) {
        console.warn('Failed to add background music:', error);
        return;
      }
    }
    
    const music = this.sounds.get('bgMusic');
    if (music && !music.isPlaying) {
      try {
        music.play();
      } catch (error) {
        console.warn('Failed to play background music:', error);
      }
    }
  }

  stopBackgroundMusic() {
    const music = this.sounds.get('bgMusic');
    if (music && music.isPlaying) {
      music.stop();
    }
  }

  pauseBackgroundMusic() {
    const music = this.sounds.get('bgMusic');
    if (music && music.isPlaying) {
      (music as Phaser.Sound.HTML5AudioSound | Phaser.Sound.WebAudioSound).pause();
    }
  }

  resumeBackgroundMusic() {
    const music = this.sounds.get('bgMusic');
    if (music && !(music as any).isPlaying) {
      (music as Phaser.Sound.HTML5AudioSound | Phaser.Sound.WebAudioSound).resume();
    }
  }

  playSound(soundKey: string) {
    if (!this.scene || this.sfxMuted) return;
    
    // Check if it's a ZzFX generated sound effect
    if (soundKey in this.zzfxSounds) {
      try {
        this.zzfxSounds[soundKey as keyof typeof this.zzfxSounds]();
      } catch (error) {
        console.warn(`Failed to play ZzFX sound ${soundKey}`, error);
      }
    } else {
      // Fallback to Phaser audio for loaded sounds
      try {
        this.scene.sound.play(soundKey, { volume: this.sfxVolume });
      } catch (error) {
        console.warn(`Sound ${soundKey} not found`, error);
      }
    }
  }

  setMusicVolume(volume: number) {
    this.musicVolume = Math.max(0, Math.min(1, volume));
    const music = this.sounds.get('bgMusic');
    if (music) {
      (music as Phaser.Sound.HTML5AudioSound | Phaser.Sound.WebAudioSound).setVolume(this.musicVolume);
    }
  }

  setSFXVolume(volume: number) {
    this.sfxVolume = Math.max(0, Math.min(1, volume));
  }

  setMusicMuted(muted: boolean) {
    this.musicMuted = muted;
    if (this.musicMuted) {
      this.pauseBackgroundMusic();
    } else {
      this.resumeBackgroundMusic();
    }
  }

  setSFXMuted(muted: boolean) {
    this.sfxMuted = muted;
  }

  isMusicMuted(): boolean {
    return this.musicMuted;
  }

  isSFXMuted(): boolean {
    return this.sfxMuted;
  }

  cleanup() {
    this.stopBackgroundMusic();
    this.sounds.clear();
    this.scene = null;
  }
}

export const soundManager = new SoundManager();
